### ISSUE TITLE
가끔 채팅을 전송해도 input value가 비워지지 않음 

### ISSUE THREAD

**Issue by hywlss9** [ATJSH/dpchat#38]
글을 전송하고 빠르게 다시 입력하면 이전 체팅 input value가 비워지지 않고 유지된다

**Comment by sos010307** [comment]
스크롤이 지멋대로 움직인다구요

**Comment by ATJSH** [comment]
확인 결과 도배 취약점에서 발생하는 문제임을 확인했습니다.

**Comment by hywlss9** [comment]
내가 이미 말한거잖아요 슈벌

2019년 6월 11일 (화) 오후 12:34, ATJSH <notifications@github.com>님이 작성:

**Comment by ATJSH** [comment]
> 내가 이미 말한거잖아요 슈벌 
다른 취약점과 함께 같이 고쳐졌다는 말을 안썻네요^_^

**Comment by hywlss9** [comment]
사퇴하세욧!!

2019년 6월 11일 (화) 오후 12:37, ATJSH <notifications@github.com>님이 작성:
