### ISSUE TITLE
도배 문제 해결해주세요

### ISSUE THREAD

**Issue by hyeongbum01** [ATJSH/dpchat#42]
채팅이 딜레이 없이 입력되니 채팅이 불가능

**Comment by MuxLee** [comment]
확인했습니다

**Comment by ATJSH** [comment]
그냥 너가 도배 안 하면 아무도 도배 안 하는 거고 도배 문제되지도 않을 텐데

**Comment by ATJSH** [comment]
채팅 친 후 300밀리세컨드 만큼 전송을 비활성화하는 방식으로 해결
